<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Website;
use App\Models\User;

class WebsitesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $admin = User::first() ?? User::create([
            'name' => 'Admin',
            'email' => 'admin@subeditor24.com',
            'password' => bcrypt('password123'),
            'role' => 'super_admin'
        ]);

        $websites = [
            [
                'name' => 'dhakapost',
                'url' => 'https://www.dhakapost.com/latest-news',
                'selector_container' => 'a.group, a[href*="/national/"], a[href*="/politics/"], a[href*="/country/"], a[href*="/sports/"]',
                'selector_title' => 'h1, h2, h3, .title, .heading',
                'selector_image' => 'img',
                'selector_content' => '.dt-news-details, .news-details, .details-content, article, p',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'bangla.bdnews24',
                'url' => 'https://bangla.bdnews24.com/',
                'selector_container' => 'a[href*="/bangladesh/"], a[href*="/politics/"], a[href*="/world/"], a[href*="/cricket/"], a[href*="/sport/"], a[href*="/opinion/"]',
                'selector_title' => 'h1, h2, h3, .title',
                'selector_image' => 'img',
                'selector_content' => '.details-brief, article, .story-content, p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'kalerkantho',
                'url' => 'https://www.kalerkantho.com/',
                'selector_container' => 'a[href*="/online/country-news/"], a[href*="/online/national/"], a[href*="/online/world/"], a[href*="/online/sport/"], a[href*="/online/entertainment/"], a[href*="/online/business/"]',
                'selector_title' => 'h1, h2, h3, .title, .heading',
                'selector_image' => 'img',
                'selector_content' => '.n_content, .article-details, .story-content, article, p',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'ekhon',
                'url' => 'https://ekhon.tv/',
                'selector_container' => 'a[href*="/national/"], a[href*="/politics/"], a[href*="/business/"], a[href*="/health/"], a[href*="/entertainment/"], a[href*="/world/"], a[href*="/sports/"]',
                'selector_title' => 'h1, h2, h3, .post-title, .title',
                'selector_image' => 'img',
                'selector_content' => '.post-details, article, .story-content, div.description, p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'bartabazar',
                'url' => 'https://bartabazar.com/',
                'selector_container' => 'a[href*="/news/"]',
                'selector_title' => 'h1, h2, h3, .entry-title',
                'selector_image' => 'img',
                'selector_content' => '.entry-content, .details-content, article, p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'bvnews24',
                'url' => 'https://www.bvnews24.com/',
                'selector_container' => 'a[href*="/news/"]',
                'selector_title' => 'h1, h2, h3, .news-title, .title',
                'selector_image' => 'img',
                'selector_content' => '.newsSection, .news-content, article, p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'dbcnews',
                'url' => 'https://dbcnews.tv/articles',
                'selector_container' => 'a[href*="/articles/"]',
                'selector_title' => 'h1, h2, h3, .title',
                'selector_image' => 'img',
                'selector_content' => '.article-details, article, .story-content, div.description, p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'ntvbd',
                'url' => 'https://www.ntvbd.com/all-news',
                'selector_container' => 'div.view-content a, h4.card-title a, a[href*="/bangladesh/"], a[href*="/world/"], a[href*="/sports/"]',
                'selector_title' => 'h1, h2, h3, .title, .heading',
                'selector_image' => 'img',
                'selector_content' => '.section-content p, .news-details, article, p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'bangla.thedailystar.net',
                'url' => 'https://bangla.thedailystar.net/todays-news',
                'selector_container' => 'div.card',
                'selector_title' => 'h3',
                'selector_image' => 'img.ratio',
                'selector_content' => 'h3.title p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'jamuna',
                'url' => 'https://jamuna.tv/latest',
                'selector_container' => '.desktopSectionLead',
                'selector_title' => 'h1, h2, h3, .title, .heading',
                'selector_image' => 'img',
                'selector_content' => '.dt-news-details, .news-details, .details-content, .article-body, .post-content, .entry-content, .story-content',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'jugantor',
                'url' => 'https://www.jugantor.com/latest',
                'selector_container' => '.desktopSectionListMedia .media',
                'selector_title' => 'h1',
                'selector_image' => 'img',
                'selector_content' => '.detailBody',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'npbnews',
                'url' => 'https://npbnews.com/latest-news',
                'selector_container' => '.row.val_page_btm .col-12',
                'selector_title' => 'h4',
                'selector_image' => 'img.images',
                'selector_content' => 'div.col-12',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'dailyamardesh',
                'url' => 'https://www.dailyamardesh.com/latest',
                'selector_container' => 'article',
                'selector_title' => 'h1',
                'selector_image' => 'img',
                'selector_content' => '.story-details p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'rtvonline',
                'url' => 'https://rtvonline.com/all-news',
                'selector_container' => '.grid',
                'selector_title' => 'h3 a',
                'selector_image' => null,
                'selector_content' => 'p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'starnews.com.bd',
                'url' => 'https://starnews.com.bd/fullnews',
                'selector_container' => 'article.post',
                'selector_title' => 'span',
                'selector_image' => 'img',
                'selector_content' => 'article.post p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'samakal',
                'url' => 'https://samakal.com/latest/news',
                'selector_container' => 'div.CatListNews',
                'selector_title' => 'h3',
                'selector_image' => 'img',
                'selector_content' => 'div.ListDesc > p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'somoynews',
                'url' => 'https://www.somoynews.tv/read/recent',
                'selector_container' => 'a[href*="/news/"], .card a',
                'selector_title' => 'h1',
                'selector_image' => 'img',
                'selector_content' => 'p',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'banglatribune',
                'url' => 'https://www.banglatribune.com/%E0%A6%86%E0%A6%9C%E0%A6%95%E0%A7%87%E0%A6%B0-%E0%A6%96%E0%A6%AC%E0%A6%B0',
                'selector_container' => 'div.row',
                'selector_title' => 'h1',
                'selector_image' => null,
                'selector_content' => 'div.content',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'bd-pratidin',
                'url' => 'https://www.bd-pratidin.com/online/todaynews',
                'selector_container' => 'section.container',
                'selector_title' => 'h1',
                'selector_image' => 'img',
                'selector_content' => 'div.card-body',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'jagonews24',
                'url' => 'https://www.jagonews24.com/latest-news',
                'selector_container' => 'div.row',
                'selector_title' => 'div',
                'selector_image' => 'img',
                'selector_content' => null,
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'bbc',
                'url' => 'https://www.bbc.com/bengali',
                'selector_container' => 'div.promo-text',
                'selector_title' => 'h3',
                'selector_image' => null,
                'selector_content' => null,
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'starnews',
                'url' => 'https://starnews.com.bd/latestnews',
                'selector_container' => 'article.post',
                'selector_title' => 'span',
                'selector_image' => null,
                'selector_content' => 'article.post p',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'itvbd',
                'url' => 'https://www.itvbd.com',
                'selector_container' => 'div.inner',
                'selector_title' => 'div',
                'selector_image' => null,
                'selector_content' => 'div.content_detail.detail',
                'use_scraping_api' => 0,
                'target_language' => 'bn',
            ],
            [
                'name' => 'channel24bd',
                'url' => 'https://www.channel24bd.tv/archives',
                'selector_container' => 'div.row',
                'selector_title' => 'Title',
                'selector_image' => null,
                'selector_content' => 'details-news-wrapper',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'ittefaq',
                'url' => 'https://www.ittefaq.com.bd/latest-news',
                'selector_container' => 'contents',
                'selector_title' => 'h1',
                'selector_image' => null,
                'selector_content' => 'div.content_detail.detail',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'mzamin',
                'url' => 'https://www.mzamin.com',
                'selector_container' => 'container',
                'selector_title' => 'h3',
                'selector_image' => null,
                'selector_content' => 'articleContent',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'prothomalo.com',
                'url' => 'https://www.prothomalo.com/collection/latest',
                'selector_container' => '.desktopSectionLead, .news-item, .post-item, article, .story-element, .news-card',
                'selector_title' => 'h1, h2, h3, .title, .heading',
                'selector_image' => 'img',
                'selector_content' => '.dt-news-details, .news-details, .details-content, .article-body, .post-content, .entry-content, .story-content',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'dawn',
                'url' => 'https://www.dawn.com/latest-news',
                'selector_container' => 'article.story',
                'selector_title' => 'h2.story__title a, a.story__link',
                'selector_image' => 'img',
                'selector_content' => '.story__content, .story-content, .article-body',
                'use_scraping_api' => 1,
                'target_language' => 'bn',
            ],
            [
                'name' => 'Aljazeera',
                'url' => 'https://www.aljazeera.com/',
                'selector_container' => 'article a.u-clickable-card__link, a.u-clickable-card__link, article h3 a',
                'selector_title' => 'span, h3, h2, .article-card__title',
                'selector_image' => 'img',
                'selector_content' => '.wysiwyg, .article__sub-header, .article-body, .article-header',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'aljazeera.com/asia/',
                'url' => 'https://www.aljazeera.com/asia/',
                'selector_container' => 'article a.u-clickable-card__link, a.u-clickable-card__link, article h3 a',
                'selector_title' => 'span, h3, h2, .article-card__title',
                'selector_image' => 'img',
                'selector_content' => '.wysiwyg, .article__sub-header, .article-body, .article-header',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'bbc.com/news/world/asia',
                'url' => 'https://www.bbc.com/news/world/asia',
                'selector_container' => 'a[href*="/news/articles/"], a[href*="/articles/"], a[data-testid="internal-link"][href*="/articles/"]',
                'selector_title' => 'h2, h1, span',
                'selector_image' => 'img',
                'selector_content' => 'article, div[data-component="text-block"], .story-body__inner, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'bbc.com/news/us-canada',
                'url' => 'https://www.bbc.com/news/us-canada',
                'selector_container' => 'a[href*="/news/articles/"], a[href*="/articles/"], a[data-testid="internal-link"][href*="/articles/"]',
                'selector_title' => 'h2, h1, span',
                'selector_image' => 'img',
                'selector_content' => 'article, div[data-component="text-block"], .story-body__inner, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'bbc.com/news/uk',
                'url' => 'https://www.bbc.com/news/uk',
                'selector_container' => 'a[href*="/news/articles/"], a[href*="/articles/"], a[data-testid="internal-link"][href*="/articles/"]',
                'selector_title' => 'h2, h1, span',
                'selector_image' => 'img',
                'selector_content' => 'article, div[data-component="text-block"], .story-body__inner, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'bbc.com/news/world/africa',
                'url' => 'https://www.bbc.com/news/world/africa',
                'selector_container' => 'a[href*="/news/articles/"], a[href*="/articles/"], a[data-testid="internal-link"][href*="/articles/"]',
                'selector_title' => 'h2, h1, span',
                'selector_image' => 'img',
                'selector_content' => 'article, div[data-component="text-block"], .story-body__inner, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'bbc.com/news/world/middle_east',
                'url' => 'https://www.bbc.com/news/world/middle_east',
                'selector_container' => 'a[href*="/news/articles/"], a[href*="/articles/"], a[data-testid="internal-link"][href*="/articles/"]',
                'selector_title' => 'h2, h1, span',
                'selector_image' => 'img',
                'selector_content' => 'article, div[data-component="text-block"], .story-body__inner, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'edition.cnn.com/world/asia',
                'url' => 'https://edition.cnn.com/world/asia',
                'selector_container' => 'a[data-link-type="article"], a[href*="/2026/"], a[href*="/2025/"]',
                'selector_title' => '.container__headline-text, span.container__headline-text, .headline__text, span',
                'selector_image' => 'img',
                'selector_content' => '.article__content, .article__content-container, .story-body, .article-body, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'edition.cnn.com/world/europe',
                'url' => 'https://edition.cnn.com/world/europe',
                'selector_container' => 'a[data-link-type="article"], a[href*="/2026/"], a[href*="/2025/"]',
                'selector_title' => '.container__headline-text, span.container__headline-text, .headline__text, span',
                'selector_image' => 'img',
                'selector_content' => '.article__content, .article__content-container, .story-body, .article-body, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'edition.cnn.com/world/middle-east',
                'url' => 'https://edition.cnn.com/world/middle-east',
                'selector_container' => 'a[data-link-type="article"], a[href*="/2026/"], a[href*="/2025/"]',
                'selector_title' => '.container__headline-text, span.container__headline-text, .headline__text, span',
                'selector_image' => 'img',
                'selector_content' => '.article__content, .article__content-container, .story-body, .article-body, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'edition.cnn.com/world/china',
                'url' => 'https://edition.cnn.com/world/china',
                'selector_container' => 'a[data-link-type="article"], a[href*="/2026/"], a[href*="/2025/"]',
                'selector_title' => '.container__headline-text, span.container__headline-text, .headline__text, span',
                'selector_image' => 'img',
                'selector_content' => '.article__content, .article__content-container, .story-body, .article-body, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'apnews',
                'url' => 'https://apnews.com/',
                'selector_container' => 'a[href*="/article/"]',
                'selector_title' => 'h1, h2, h3, .Page-headline',
                'selector_image' => 'img',
                'selector_content' => '.RichTextStoryBody, .StoryBody, [data-key="article-body"], .Page-content, .article-body, article',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'voanews',
                'url' => 'https://www.voanews.com/',
                'selector_container' => 'a[href*="/a/"]',
                'selector_title' => 'h1, .title, .page-header, .media-block__title',
                'selector_image' => 'img',
                'selector_content' => '.body-content, .wsw, #article-content, .article__body, main',
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
            [
                'name' => 'thedailystar',
                'url' => 'https://www.thedailystar.net/',
                'selector_container' => '.desktopSectionLead, .news-item, .post-item, article, .story-element, .news-card',
                'selector_title' => 'h1, h2, h3, .title, .heading',
                'selector_image' => null,
                'selector_content' => null,
                'use_scraping_api' => 1,
                'target_language' => 'en',
            ],
        ];

        foreach ($websites as $site) {
            Website::withoutGlobalScopes()->updateOrCreate(
                ['url' => $site['url']],
                array_merge($site, ['user_id' => $admin->id])
            );
        }
    }
}
